refactor(ci): remove unnecessary matrices

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,32 +17,15 @@ env:
 
 jobs:
   lint:
-    strategy:
-      matrix:
-        os: [ubuntu-latest]
-    runs-on: ${{ matrix.os }}
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: Set up environment
         uses: ./.github/actions/setup-env
       - run: mono lint
 
-  test-unit:
-    strategy:
-      matrix:
-        os: [ubuntu-latest]
-    runs-on: ${{ matrix.os }}
-    steps:
-      - uses: actions/checkout@v4
-      - name: Set up environment
-        uses: ./.github/actions/setup-env
-      - run: mono test unit
-
-  test-integration-node-sync:
-    strategy:
-      matrix:
-        os: [ubuntu-latest]
-    runs-on: ${{ matrix.os }}
+  test:
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: Set up environment
@@ -57,6 +40,9 @@ jobs:
           echo "OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp-gateway-prod-us-east-2.grafana.net/otlp" >> $GITHUB_ENV
           # Disable in Vite (otherwise CORS issues)
           echo "VITE_OTEL_EXPORTER_OTLP_ENDPOINT=" >> $GITHUB_ENV
+      - run: mono test unit
+      - run: mono test integration misc
+      - run: mono test integration todomvc
       - run: mono test integration node-sync
       - name: Display node-sync logs
         if: always()
@@ -80,52 +66,24 @@ jobs:
           name: node-sync-logs
           path: tests/integration/tmp/logs/
           retention-days: 30
+      # - run: mono test integration devtools
+      # TODO fix flaky devtools test
+      - run: mono test integration devtools || echo "::warning::Script failed but continuing"
 
-  test-integration-playwright:
-    strategy:
-      matrix:
-        os: [ubuntu-latest]
-        suite: [misc, todomvc, devtools]
-    runs-on: ${{ matrix.os }}
-    steps:
-      - uses: actions/checkout@v4
-      - name: Set up environment
-        uses: ./.github/actions/setup-env
-      - name: Set OTEL_EXPORTER_OTLP_HEADERS environment variable
-        env:
-          GRAFANA_CLOUD_OTLP_INSTANCE_ID: 1227256
-          GRAFANA_CLOUD_OTLP_API_KEY: ${{ secrets.GRAFANA_CLOUD_OTLP_API_KEY }}
-        run: |
-          echo "OTEL_EXPORTER_OTLP_HEADERS=Authorization=Basic $(echo -n "$GRAFANA_CLOUD_OTLP_INSTANCE_ID:$GRAFANA_CLOUD_OTLP_API_KEY" | base64 -w 0)" >> $GITHUB_ENV
-          echo "GRAFANA_ENDPOINT=https://livestore.grafana.net" >> $GITHUB_ENV
-          echo "OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp-gateway-prod-us-east-2.grafana.net/otlp" >> $GITHUB_ENV
-          # Disable in Vite (otherwise CORS issues)
-          echo "VITE_OTEL_EXPORTER_OTLP_ENDPOINT=" >> $GITHUB_ENV
-      - name: Run integration tests
-        env:
-          PLAYWRIGHT_SUITE: ${{ matrix.suite }}
-        run: |
-          if [ "${{ matrix.suite }}" = "devtools" ]; then
-            # TODO fix flaky devtools test
-            mono test integration devtools || echo "::warning::Script failed but continuing"
-          else
-            mono test integration ${{ matrix.suite }}
-          fi
       - uses: actions/upload-artifact@v4
         if: ${{ !cancelled() }}
         with:
-          name: playwright-report-${{ matrix.suite }}
+          name: playwright-report
           path: tests/integration/playwright-report/
           retention-days: 30
       - name: "Upload trace"
         if: ${{ !cancelled() }}
         env:
           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
-          PLAYWRIGHT_SUITE: ${{ matrix.suite }}
           # TODO surface deploy url in github UI via environments
         run: |
           if [ -n "$NETLIFY_AUTH_TOKEN" ]; then
-            bunx netlify-cli deploy --no-build --dir=tests/integration/playwright-report --site livestore-ci --filter @local/tests-integration --alias ${{ matrix.suite }}-$(git rev-parse --short HEAD)
+            bunx netlify-cli deploy --no-build --dir=tests/integration/playwright-report --site livestore-ci --filter @local/tests-integration
           else
             echo "Skipping Netlify deploy: NETLIFY_AUTH_TOKEN not set"
           fi
@@ -152,11 +110,8 @@ jobs:
 
   publish-snapshot-version:
     if: github.event.pull_request.head.repo.fork != true
-    strategy:
-      matrix:
-        os: [ubuntu-latest]
-    runs-on: ${{ matrix.os }}
-    needs: [test-unit, test-integration-node-sync, test-integration-playwright]
+    needs: test
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: Set up environment
@@ -169,10 +124,7 @@ jobs:
       - run: mono release snapshot --git-sha=${{ github.sha }}
 
   build-and-deploy-examples-src:
-    strategy:
-      matrix:
-        os: [ubuntu-latest]
-    runs-on: ${{ matrix.os }}
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: Set up environment
@@ -186,10 +138,7 @@ jobs:
           VITE_LIVESTORE_SYNC_URL: 'https://websocket-server.schickling.workers.dev'
 
   build-deploy-docs:
-    strategy:
-      matrix:
-        os: [ubuntu-latest]
-    runs-on: ${{ matrix.os }}
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: Set up environment
@@ -201,12 +150,11 @@ jobs:
 
   build-examples-tiged:
     if: github.event.pull_request.head.repo.fork != true
+    needs: publish-snapshot-version
     strategy:
       matrix:
         app: [web-todomvc, web-linearlite, expo-linearlite]
-        os: [ubuntu-latest]
-    runs-on: ${{ matrix.os }}
-    needs: [publish-snapshot-version]
+    runs-on: ubuntu-latest
     env:
       APP_PATH: examples/${{ matrix.app }}
       SNAPSHOT_VERSION: "0.0.0-snapshot-${{ github.sha }}"
